### ISSUE TITLE
【微調整】画像、文字、ダウンロードPDF、注、ほか

### ISSUE THREAD

**Issue by fruitsnoodle** [o2project/steins-git#95]
- [x] 画像：モノクロで今画像に書かれている面白い文字が見難くなっています。はっきり見えるように調整をお願いします。
- [x] 文字：本文の文字を全部黒くする。
- [ ] ダウンロードPDF版：中身カラー（タイトル、キャプチャなど）でいい
- [x] 注：fruitsnoodleの注を全部GitHubアカウントに統一
- [x] 注：GiantRobotの印刷版は「pixivID:1223059」に変更、ダウンロード用PDFは直リンクでOK。
- [x] ほか：役割「雑務」を「アシスタント」か「マネージャー」に変更

**Comment by kubosho** [comment]
残っているやつは #120 で対応
